# Generated by Django 3.1.2 on 2020-11-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20201108_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='publication_date',
            field=models.DateTimeField(),
        ),
    ]
