# Generated by Django 3.1.2 on 2020-11-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20201115_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
