# Generated by Django 3.1.2 on 2020-11-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20201115_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-publication_date']},
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Tiempo Completo', 'Tiempo Completo'), ('Remoto', 'Remoto'), ('Medio Tiempo', 'Medio Tiempo'), ('Freelance', 'Freelance')], max_length=200, null=True),
        ),
    ]
